---
- hosts: all
  roles:

  tasks:

  - name: add epel-8 repository 
    yum_repository:
       name: epel-8
       description: epel-8
       baseurl: http://scl06i-9851.equity.csfb.com/repos/epel-8
       enabled:  yes
       gpgcheck: no
    when:
      - ansible_distribution_major_version == "8"

  - name: add epel-7 repository 
    yum_repository:
       name: epel-7
       description: epel-7
       baseurl: http://scl06i-9851.equity.csfb.com/repos/epel-7
       enabled:  yes
       gpgcheck: no
    when:
      - ansible_distribution_major_version == "7"

  - name: install benchmark tool rpms
    yum:
      name:
         -  LLsysjitter
         -  LLsockperf
         -  LLIntelMLC
         -  LLlmbench
         -  ioping
         -  perf
      state: latest
