---
- hosts: all
  roles:

  tasks:

  - name: remnove benchmark tool rpms
    yum:
      name:
         -  LLsysjitter
         -  LLsockperf
         -  LLIntelMLC
         -  LLlmbench
         -  ioping
         -  perf
      state: absent
