---
- name: Include crowdstrike
  include_vars: "{{ roles_path }}/crowdstrike/vars/crowdstrike.yml"

- name: set short date
  shell: "date +%d%m%y"
  register: tstamp
  when:
   - ansible_distribution_major_version|int >= 7

- name: Get List of services
  service_facts:

- name: Output message is Crowdstrike missing
  shell: "{{ item }}"
  with_items:
    - "{{ crowdstrike_missing }}"
  when:
    - "'falcon-sensor.service' not in services"

#- name: Stop cgroups service
#  shell: "{{ item }}"
#  with_items:
#    - "{{ LLcgconfig_stop }}"
#  when:
#    - "'LLcgconfig' in services"

- name: run {{ prog }} tests
  async: 60
  poll: 0

  shell: "{{ item }}"
  with_items:
    - "{{ commands }}"
  when:
   - "'falcon-sensor.service' in services"
   - ansible_distribution_major_version|int >= 7

  environment:
   PATH: '{{ ansible_env.PATH }}:{{ prog_path }}'

- name: Start cgroups service
  shell: "{{ item }}"
  with_items:
     - "{{ LLcgconfig_start }}"
  when:
     - "'LLcgconfig' in services"

- name: find file on remote to copy
  find:
    paths: /tmp/
    recurse: no
    patterns:
      - "{{ prog }}.log.{{ tstamp.stdout }}.txt"
  register: files_to_copy
  when:
   - ansible_distribution_major_version|int >= 7

- name: Copy logfile(s) to control server
  fetch:
     src: "{{ item.path }}"
     dest: "{{ logs_dir }}/{{ ansible_hostname }}.{{ prog }}.log.{{ tstamp.stdout }}.txt"
     flat: yes
  with_items: "{{ files_to_copy.files }}"
  when:
    - ansible_distribution_major_version|int >= 7

- name: local action on controller to fix fetched file perms
  file:
     path: "{{ logs_dir }}"
     mode: 0755
     recurse: yes
  delegate_to: localhost
  when:
    - ansible_distribution_major_version|int >= 7
